language: objective-c
script: 
- travis_wait 40 xcodebuild -project build/macosx/ml.xcodeproj -scheme "BUILD ALL MAX" -configuration Deployment | grep "[Ee]rror:"
- travis_wait 40 xcodebuild -project build/macosx/ml.xcodeproj -scheme "BUILD ALL PD" -configuration Deployment | grep "[Ee]rror:"

