language: objective-c
script: 
  - xcodebuild -project build/macosx/ml.xcodeproj -scheme "BUILD ALL MAX" -configuration Deployment | grep [Ee]rror:
  - xcodebuild -project build/macosx/ml.xcodeproj -scheme "BUILD ALL PD" -configuration Deployment | grep [Ee]rror:
