language: cpp
script: xcodebuild -project ml.xcodeproj -scheme "BUILD ALL MAX" -configuration Deployment CONFIGURATION_BUILD_DIR=./Release
script: xcodebuild -project ml.xcodeproj -scheme "BUILD ALL PD" -configuration Deployment CONFIGURATION_BUILD_DIR=./Release
