language: objective-c
script: xcodebuild -project build/macosx/ml.xcodeproj -scheme "BUILD ALL MAX" -configuration Deployment | grep -A 5 error:
script: xcodebuild -project build/macosx/ml.xcodeproj -scheme "BUILD ALL PD" -configuration Deployment | grep -A 5 error:
